name: mobile
description: Hazizz Mobile application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  dropdown_menu: 1.1.1
  url_launcher: ^5.0.2
  flutter_svg: 0.14.0
  uni_links: 0.2.0
  package_info: 0.4.0+6

  font_awesome_flutter: 8.5.0

  toast: ^0.1.5
  image_picker: 0.6.1+2

  image_cropper:
    git:
      url: git://github.com/devslane/flutter_image_cropper
      ref: master

  logger: 0.7.0+2
  #logger_flutter: 0.7.0

  workmanager: 0.0.15

  firebase_dynamic_links: 0.5.0+1
  flutter_auth_buttons: 0.5.0
  firebase_analytics: 4.0.1
  google_sign_in: 4.0.4
  firebase_auth: 0.11.1+11
  firebase_crashlytics: 0.1.0+2
  firebase_core: ^0.4.0+6
  android_alarm_manager: 0.4.4
  dynamic_theme: 1.0.1
  sticky_header_list: 1.0.6
  auto_size_text: 2.0.1
  preferences: 4.0.0
  share: 0.6.1
  easy_localization: 1.0.3+1
  equatable: 0.3.0
  flutter_bloc: ^0.20.0
  expandable: 3.0.0+1
  intl: 0.15.8
  flutter_local_notifications: 0.8.2
  sticky_headers: 0.1.8

  dio: 2.1.13

  cookie_jar: 1.0.1
  connectivity: 0.4.3+6
  shared_preferences: 0.5.3+4
  json_annotation: 2.3.0
  http: ^0.12.0+2
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 2.3.0
  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   # - assets/
   # - assets/images/
    - assets/images/Logo.png
    - assets/images/hatter-1.svg
    - assets/images/hatter-2.svg
    - assets/images/hatter-3.svg

   # - assets/images/notebook_background.svg
    - assets/images/notebook_background.png
  #  - assets/images/notebook_background1.png


    - assets/langs/en.json
    - assets/langs/hu.json
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-RegularItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 900
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
