name: mobile
description: Hazizz Mobile application.

version: 1.4.12+55

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  edit_distance: 0.4.1

  flutter_widgets: 0.1.11

  json_navigation_saver: 0.2.1
  build_value_navigation_saver: ^0.2.1
  shared_pref_navigation_saver: ^0.2.1

  uuid: 2.0.4
  permission_handler: 4.4.0
  image_gallery_saver: 1.2.2
  native_state: 1.0.2
  photo_view: 0.9.2
  googleapis: 0.54.0
  flutter_image_compress: 0.6.5+1
  steel_crypt: 1.6.1
  image: 2.1.4 # 2.1.12
  flutter_markdown:
    path: ./lib/custom/flutter_markdown

  firebase_messaging: 6.0.12
  animator: 1.0.0+5
  flutter_mailer: 0.4.2
  path_provider: 1.6.0
  logcat:
    path: ./lib/custom/logcat/logcat-master
  fl_chart: 0.8.3
  snappable: 1.0.1
  table_calendar: 2.2.2
  flushbar: 1.9.1
  dio_flutter_transformer: 3.0.2 # 2.0.10

  progress_dialog: 1.2.0
  dropdown_menu: 1.1.1
  url_launcher: ^5.4.1
  flutter_svg: 0.17.1
  uni_links: 0.2.0
  package_info: 0.4.0+14

  font_awesome_flutter: 8.7.0

  toast: ^0.1.5
  image_picker: 0.6.3+4 #image_picker: ^0.4.12
 # image_cropper:
 #   git:
 #     url: git://github.com/devslane/flutter_image_cropper
 #     ref: master

  logger: 0.8.3
  #logger_flutter: 0.7.0

 # workmanager: 0.1.4

  firebase_dynamic_links: 0.5.0+11
  flutter_auth_buttons: 0.6.0
  firebase_analytics: 5.0.11
  flutter_facebook_login: 3.0.0
  google_sign_in: 4.4.1
  firebase_auth: 0.14.0+5
  firebase_crashlytics: 0.1.3
  firebase_core: ^0.4.3+2
  android_alarm_manager: 0.4.4
  dynamic_theme: 1.0.1
  auto_size_text: 2.1.0
  preferences: 5.0.1
  share: 0.6.3+1
  easy_localization: 1.3.2
  equatable: 0.3.0
  flutter_bloc: ^0.20.0
  expandable: 3.0.1
  intl: 0.16.0
  flutter_local_notifications: 0.8.4
  sticky_headers: 0.1.8+1

  dio: 3.0.9

  cookie_jar: 1.0.1
  connectivity: 0.4.8+1
  shared_preferences: ^0.5.6
  json_annotation: ^3.0.1 # 2.3.0
  http: ^0.12.0+4
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5 #2.3.0
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Icon.png"
  adaptive_icon_background: "#4AD9D9"

flutter:
  uses-material-design: true
  assets:
   # - assets/
    - assets/images/
    - assets/icons/discord.svg
    - assets/icons/facebook.svg
    - assets/icons/github.svg
    - assets/icons/twitter.svg
    - assets/images/Logo.png
    - assets/images/hatter-1.svg
    - assets/images/hatter-2.svg
    - assets/images/hatter-3.svg

   # - assets/images/notebook_background.svg
    - assets/images/notebook_background.png
  #  - assets/images/notebook_background1.png
    - assets/images/facebook_ad_banner.png
    - assets/images/fel_elek_ad_banner.png
    - assets/images/giveaway_ad_banner.png
    - assets/images/hazizz_meet_ad_banner.png
    -
    - assets/langs/en.json
    - assets/langs/hu.json
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-RegularItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 900
          style: italic