name: mobile
description: Hazizz Mobile application.

version: 1.5.5+72

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter_form_builder: 3.10.1

  ffloat: 1.0.1
  statsfl: 0.1.0

  edit_distance: 0.4.1

  scrollable_positioned_list: 0.1.5

  uuid: 2.0.4
  permission_handler: 5.0.0+hotfix.6
  image_gallery_saver: 1.2.2
  native_state: 1.0.2
  photo_view: 0.9.2
  googleapis: 0.55.0
  flutter_image_compress: 0.6.8
 # steel_crypt: 1.7.1+1
  image: 2.1.12 # 2.1.4
  flutter_markdown: 0.4.1

  firebase_messaging: 6.0.13
  animator: 1.0.0+5
  flutter_mailer: 0.5.0-dev.7
  path_provider: 1.6.7
  logcat: 1.0.2
  fl_chart: 0.8.3
  snappable: 1.0.1
  table_calendar: 2.2.3
  flushbar: 1.10.4
  dio_flutter_transformer: 3.0.2

  progress_dialog: 1.2.3
  url_launcher: ^5.4.1
  flutter_svg: 0.17.2
  uni_links: 0.4.0
  package_info: 0.4.0+17

  font_awesome_flutter: 8.8.1

  flutter_styled_toast: 1.3.1
  image_picker: 0.6.6+5

  logger: 0.9.1

  firebase_dynamic_links: 0.5.1
  flutter_auth_buttons: 0.8.0
  firebase_analytics: 5.0.10
  flutter_facebook_login:
    git:
      url: 'https://github.com/romulojjunior/flutter_facebook_login.git'
      ref: feature/web_support
  google_sign_in: 4.5.1 # 4.4.4 broke logging in # 4.4.1
  firebase_auth: 0.16.1
  firebase_crashlytics: 0.1.3+3
  firebase_core: ^0.4.3+2
  android_alarm_manager: 0.4.5+11
  dynamic_theme: 1.0.1
  auto_size_text: 2.1.0
  preferences: 5.2.0
  share: 0.6.4+3
  easy_localization: 2.3.2 # 1.3.2
  equatable: 1.1.1 # 0.3.0
  flutter_bloc: 4.0.0
  expandable: 4.1.4
  intl: 0.16.1
  flutter_local_notifications: 1.4.3
  sticky_headers: 0.1.8+1

  dio: 3.0.9

  cookie_jar: 1.0.1
  connectivity: 0.4.9
  shared_preferences: ^0.5.7+1
  json_annotation: ^3.0.1 # 2.3.0
  http: ^0.12.1 # 0.+4
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5 #2.3.0
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Icon.png"
  adaptive_icon_background: "#4AD9D9"

flutter:
  uses-material-design: true
  assets:
   # - assets/
    - assets/images/
    - assets/icons/discord.svg
    - assets/icons/facebook.svg
    - assets/icons/github.svg
    - assets/icons/twitter.svg
    - assets/images/Logo.png
    - assets/images/hatter-1.svg
    - assets/images/hatter-2.svg
    - assets/images/hatter-3.svg

   # - assets/images/notebook_background.svg
    - assets/images/notebook_background.png
    - assets/images/vakacio_background.png
  #  - assets/images/notebook_background1.png
    - assets/images/facebook_ad_banner.png
    - assets/images/fel_elek_ad_banner.png
    - assets/images/giveaway_ad_banner.png
    - assets/images/hazizz_meet_ad_banner.png
    - assets/images/elek_sleep.svg

    - assets/langs/en.json
    - assets/langs/hu.json
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-RegularItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 900
          style: italic